{
 "title": "Logging dashboards",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Cluster logs",
   "type": "logs",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{ecs_cluster=\"ecs-cluster\"}"
    }
   ]
  },
  {
   "title": "API Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "{container_name=~\"/ecs-toptal-prod-api.+\"}"
    }
   ]
  },
  {
   "title": "WEB Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "{container_name=~\"/ecs-toptal-prod-web.+\"}"
    }
   ]
  }
 ]
}